[tool.poetry]
name = "oop"
version = "0.1.0"
description = ""
authors = ["Gleb <ghliebp@bk.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
pytest = "^8.4.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
